name: ci
on: [deployment_status]
jobs:
  deploy:
    # only runs this job on successful deploy
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Bunny CDN Purge Cache
        run: |
          curl --request POST \
              --url https://api.bunny.net/pullzone/${{ secrets.BUNNY_ZONE }}/purgeCache \
              --header 'AccessKey: ${{ secrets.BUNNY_TOKEN }}'